### ISSUE TITLE
Installation error!

### ISSUE THREAD

**Issue by niuniu688** [gitover22/HF_DFS#1]
When I deployed this system, I first configured nginx and then fastDFS, but when using nginx to connect multiple nodes, the client in the browser could not properly identify the target forwarding node：
![image](https://github.com/user-attachments/assets/6a080267-6adf-44bf-8d84-cb4e3901a2ed)

**Comment by gitover22** [comment]
hello，according to your description，i think you can try：
1：you can check your nginx server :
```
sudo systemctl status nginx
```
start:
```
sudo systemctl start nginx
```
2: Check your server's firewall
3: Check your Nginx configuration file to make sure that listen and server_name are set correctly,such as:
```
server {
    listen 80;
    server_name 172.17.199.190; # make sure this correct
}
```

**Comment by niuniu688** [comment]
> hello，according to your description，i think you can try： 1：you can check your nginx server :
> 
> ```
> sudo systemctl status nginx
> ```
> 
> start:
> 
> ```
> sudo systemctl start nginx
> ```
> 
> 2: Check your server's firewall 3: Check your Nginx configuration file to make sure that listen and server_name are set correctly,such as:
> 
> ```
> server {
>     listen 80;
>     server_name 172.17.199.190; # make sure this correct
> }
> ```

oh,thanks,I wrote my config file wrong
